services:
  redis:
    image: redis:7
    container_name: Redis_2
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    container_name: MySql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_db