server:
  port: 8080

spring:
  application:
    name: java-excercise


  datasource:
    url: jdbc:mysql://localhost:3308/swappie_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  app:
    scrKey: "ftMUk2/X4NO1FHWJNkVqu2ZdbLXuSTW2FFiI+r3mGhQqc0eD+ehhrrG63Ru6yJtnmCoJPm8sOKVvhl4OqgHouw=="
  data:
    redis:
      host: localhost
      port: 6380