### Update customer
@id = 3cf82d47-033b-4237-a69b-648d8e49bbea
PUT http://localhost:4000/customers/{{id}}
Content-Type: application/json

{
  "email": "phatlee1104@gmail.com",
  "firstName": "Hiep Phat",
  "lastName": "Le",
  "address": "Main street, 123",
  "phoneNumber": "0963116549"
}

###